"""add inviter tables (invite_campaigns, invite_tasks, invite_logs)

Revision ID: 20260609_000001
Revises: 20260602_000001
Create Date: 2026-06-09 14:55:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "20260609_000001"
down_revision = "20260602_000001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invite_campaigns",
        sa.Column("owner_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False, index=True),
        sa.Column("source_chat_id", sa.BigInteger(), nullable=True),
        sa.Column("source_chat_title", sa.String(length=255), nullable=True),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("target_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("target_chat_title", sa.String(length=255), nullable=True),
        sa.Column("target_chat_username", sa.String(length=255), nullable=True),
        sa.Column("daily_limit_per_account", sa.Integer(), nullable=False),
        sa.Column("invite_delay_min", sa.Integer(), nullable=False),
        sa.Column("invite_delay_max", sa.Integer(), nullable=False),
        sa.Column("pause_after_every", sa.Integer(), nullable=False),
        sa.Column("pause_duration_min", sa.Integer(), nullable=False),
        sa.Column("pause_duration_max", sa.Integer(), nullable=False),
        sa.Column("warmup_enabled", sa.Boolean(), nullable=False),
        sa.Column("warmup_days", sa.Integer(), nullable=False),
        sa.Column("warmup_limit_factor", sa.Float(), nullable=False),
        sa.Column("only_add_contacts", sa.Boolean(), nullable=False),
        sa.Column("add_to_contacts_first", sa.Boolean(), nullable=False),
        sa.Column("blacklist_usernames", sa.Text(), nullable=True),
        sa.Column("blacklist_user_ids", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name="fk_invite_campaigns_owner_id_users"),
        sa.PrimaryKeyConstraint("id", name="pk_invite_campaigns"),
    )
    op.create_index("ix_invite_campaigns_owner_id", "invite_campaigns", ["owner_id"])

    op.create_table(
        "invite_tasks",
        sa.Column("campaign_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("account_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("proxy_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("target_user_id", sa.BigInteger(), nullable=False, index=True),
        sa.Column("target_username", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False, index=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=32), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("invited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["invite_campaigns.id"], name="fk_invite_tasks_campaign_id_invite_campaigns"),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], name="fk_invite_tasks_account_id_accounts"),
        sa.ForeignKeyConstraint(["proxy_id"], ["proxies.id"], name="fk_invite_tasks_proxy_id_proxies"),
        sa.PrimaryKeyConstraint("id", name="pk_invite_tasks"),
    )

    op.create_table(
        "invite_logs",
        sa.Column("invite_task_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_code", sa.String(length=32), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(["invite_task_id"], ["invite_tasks.id"], name="fk_invite_logs_invite_task_id_invite_tasks"),
        sa.PrimaryKeyConstraint("id", name="pk_invite_logs"),
    )
    op.create_index("ix_invite_logs_action", "invite_logs", ["action"])
    op.create_index("ix_invite_logs_success", "invite_logs", ["success"])


def downgrade() -> None:
    op.drop_table("invite_logs")
    op.drop_table("invite_tasks")
    op.drop_table("invite_campaigns")
